### ISSUE TITLE
Implement Node:normalize()

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#21]
https://dom.spec.whatwg.org/#dom-node-normalize

**Comment by craigbarnes** [comment]
This could also replace the [workaround](https://github.com/craigbarnes/lua-gumbo/blob/5e333e78fb583fd6d70ddc65b0145edc74704f62/test/tree-construction.lua#L61-L69) in `test/tree-construction.lua`.

**Comment by daurnimator** [comment]
not bothering with this?

**Comment by craigbarnes** [comment]
Probably not. A tree returned by `gumbo.parse()` shouldn't require it and it's easy enough to avoid needing it when mutating the DOM. Also, reading the spec gives me a headache.
