### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#44]
As [mentioned] by @daurnimator, the bindings currently leak the heap-allocated `GumboOutput` if an error is thrown during parsing (unlikely, [but][] [possible]). ~~A finalizer should be used (via [`ffi.gc`] or [`__gc`]) to prevent leaks even in the case of errors~~.

[but]: https://github.com/craigbarnes/lua-gumbo/blob/5e333e78fb583fd6d70ddc65b0145edc74704f62/gumbo/parse.c#L159
[possible]: https://github.com/craigbarnes/lua-gumbo/blob/5e333e78fb583fd6d70ddc65b0145edc74704f62/gumbo/parse.c#L219
[mentioned]: https://github.com/craigbarnes/lua-gumbo/issues/41#issuecomment-87640880
[`ffi.gc`]: http://luajit.org/ext_ffi_api.html#ffi_gc
[`__gc`]: http://www.lua.org/manual/5.2/manual.html#2.5.1

**Comment by craigbarnes** [comment]
I've been thinking about how to do this properly for a while now. All I have to say so far is that combining C heap allocation and Lua error handling is a godawful mess.

**Comment by daurnimator** [comment]
It's easy if you can allocate on the lua stack: use `lua_newuserdata` instead of `malloc`.

**Comment by craigbarnes** [comment]
@daurnimator The `malloc` is done via `gumbo_parse_with_options`. It's currently possible to pass a custom allocator to Gumbo, but there's talk of removing it.

**Comment by daurnimator** [comment]
(well you should do that anyway, but that's tangential to this issue).

Shouldn't you just be able to attach the metatable before you do anything else?
i.e. move the `setmetatable` call up to just after https://github.com/craigbarnes/lua-gumbo/blob/5e333e78fb583fd6d70ddc65b0145edc74704f62/gumbo/parse.c#L232

**Comment by daurnimator** [comment]
oh, the metatable doesn't *have* a __gc metamethod; as the returned value is not a userdata, but a table.

**Comment by craigbarnes** [comment]
I was thinking about storing the pointer as a lightuserdata field and checking/freeing that in `__gc`. The metatable would have to be set before anything else though, yes. I started implementing it a while back and gave up. I really should close this issue before I release 0.4 though.

**Comment by daurnimator** [comment]
In that case, all you need is to wrap your code in a `pcall`.
  - Move https://github.com/craigbarnes/lua-gumbo/blob/5e333e78fb583fd6d70ddc65b0145edc74704f62/gumbo/parse.c#L233-L248 to it's own lua_function
  - `lua_pcall` it
  - Handle the pcall result after you destory the gumbo object

Free bonus is you can now have `return nil, "error message"` semantics for *all* errors :)

**Comment by craigbarnes** [comment]
@daurnimator Many thanks for the suggestion. It's a much cleaner solution than the idea I had.

This issue is now mostly fixed. There's just the one [`TODO`](https://github.com/craigbarnes/lua-gumbo/commit/da15e2843a0bec5538a08b0526e6f947f6211c94#diff-a8090840a9c73b86a781c3f9ad3b6f7cR269) remaining.
