### ISSUE TITLE
Fix Travis build

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#45]
* [x] ~~Homebrew deleted their Lua 5.2 package;~~ replace Homebrew with something actually reliable.
* [x] The apt/brew packages for Gumbo are out of date, since `master` targets 0.10.x now -- just fetch and install Gumbo manually instead.

**Comment by istr** [comment]
I know that [this is an old discussion](https://github.com/craigbarnes/lua-gumbo/pull/27#issuecomment-65234482), but why not simply clone [what works simply and reliably with the new travis infrastructure](https://travis-ci.org/moteus/lua-travis-example) from [here, even if based on scripts](https://github.com/moteus/lua-travis-example) now that the osx packager has proven to be shoddy, too?
I would like to try a solution that clones lua-travis-example, just like you proposed in your old PR comment...

**Comment by craigbarnes** [comment]
Yes, that would be the best option now. I'll gladly merge a PR that does so. Otherwise, I'll get around to it eventually.

**Comment by istr** [comment]
Ok; [made some experiments on a separate branch](https://github.com/istr/lua-gumbo/tree/travis-new). Seems that I need to fork https://github.com/istr/lua-travis-example, because it won't provide a [pkg-config file](http://www.linuxfromscratch.org/blfs/view/svn/general/lua.html) yet. Working around that is not that easy with the current ```lualib.mk``` and ```Makefile``` setup, so better provide a generated pkg-config file in the travis helper repo (that would make the travis helper more useful and won't mess with the current lua-gumbo build setup, that is quite good imho).

**Comment by daurnimator** [comment]
> Homebrew deleted their Lua 5.2 package

They did? looks fine to me: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/lua.rb

**Comment by istr** [comment]
[They](https://github.com/Homebrew/homebrew/issues/14538) [kind of](https://github.com/Homebrew/homebrew/issues/25988) [did](https://github.com/Homebrew/homebrew/issues/32354).
Maybe there is a way, though, to tweak the travis build to use what is provided there.
It is kind of strange that there was a build [that worked with 5.2 but not with 5.1 / LuaJIT](https://travis-ci.org/craigbarnes/lua-gumbo/builds/52326630), though. I will try to investigate further.

**Comment by craigbarnes** [comment]
Just pushed a few commits to begin fixing this. I've opted to just fetch and build Lua manually. I know I originally objected to that idea, but I'm losing faith in package managers and Lua is tiny to download and quick to build anyway.

Todo:

* [ ] Add LuaJIT and Lua 5.1.5 to test matrix (the 5.1.5 build seems broken currently)
* [ ] Verify SHA1 sums of downloaded tarballs..?
* [ ] Test `pkg-config` build (just latest Lua and LuaJIT on Linux only)..?

**Comment by craigbarnes** [comment]
> Working around that is not that easy with the current lualib.mk and Makefile setup, so better provide a generated pkg-config file...

All the variables in the Makefile that call `pkg-config` are lazily evaluated. If you manually set a variable that would have otherwise expanded to a `$(shell pkg-config ...)` call, Make will stop recursive expansion right there and use whatever you've given it (i.e. `pkg-config` won't even be called).

For example, the `check-lua-all` target overrides enough variables to not call out to `pkg-config` even once. The Travis `script` also sets `LUA_PC` to an invalid/non-existent name, to ensure that it throws an error if it ever tries to call `pkg-config` somehow.

**Comment by craigbarnes** [comment]
I think I can close this issue, since Travis is now running all tests against Lua 5.1/5.2/5.3 and LuaJIT 2.0/2.1-beta1. The remaining few todo items can be opened as separate issues.
