### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Jesdisciple** [craigbarnes/lua-gumbo#47]
This library seems to inherit a dependency on Linux from Gumbo proper, but I can't find confirmation of that anywhere. (I can't even confirm it for the Google C library.) If that's true, are there any plans to port to Windows?

I have a little project I just started in order to (re)learn Lua, and it involves traversing a DOM... Maybe I need a different project.

**Comment by craigbarnes** [comment]
I don't think Gumbo has ever had a dependency on Linux specifically, but until recently, it was written in C99 without any regard for the fact that MSVC doesn't (or didn't) fully support C99. I think various patches were submitted a while back to allow the library to compile on Windows, but I'm not sure to what extent it is supported.

The situation with lua-gumbo is basically that no effort whatsoever has been put into Windows support or testing. If someone is willing to figure out what needs to be done to support Windows and send patches to implement it, I can see about merging them, but I don't intend to do any Windows development or testing myself.

**Comment by Jesdisciple** [comment]
Alright, thanks for the response. I suggest a note in the documentation about platform support (or C99 support in platforms); that I couldn't find one seemed odd.

While this looks like a cool project, I prefer other flavors of punishment. I hope you find someone to fill that gap, though, because this should be available (on Windows, in Lua).

**Comment by craigbarnes** [comment]
Point taken about mentioning it in the docs. I'll add a note about platform support.

In theory, the lua-gumbo C code shouldn't need much, if any, patching like Gumbo itself did. The main thing missing is a Windows-compatible build system.
