### ISSUE TITLE
 Implement ParentNode.querySelector() and ParentNode.querySelectorAll()

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#5]
https://dom.spec.whatwg.org/#dom-parentnode-queryselector

Requires:
- [x] Selector parser (552383e8fbdbb14d09497145f56963afcc692e33)
- [ ] Code generator
- [ ] Tree walker

**Comment by dai-yamashita** [comment]
When will this function be implemented? I am very much looking forward to it.

I can cooperate only with the test and use after implementation, but this library is very useful and looking forward to it.

**Comment by dai-yamashita** [comment]
Will it be in the intended shape if you incorporate https://github.com/lazytiger/gumbo-query well?

**Comment by craigbarnes** [comment]
> When will this function be implemented?

I guess when someone finishes the large amount of work required. Personally, I don't have any time to work on it for 2-3 months at least.

Everything that can be done with selector matching can currently be done using custom tree walkers. The `querySelectorAll` API is mostly useful for readability/familiarity purposes.

**Comment by craigbarnes** [comment]
I have decided that implementing and maintaining this correctly would be too much work to do "just because". Until I have a real world need for it myself or for a paying client, I'm afraid I'm not going to be working on it.
