### ISSUE TITLE
Add separate parseFragment function

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#51]
The API of the `parse` function has changed since the 0.3 release from:

```lua
local document = gumbo.parse(html, tabStop)
```

...to:

```lua
local document = gumbo.parse(html, ctx, ctxns, tabStop)
```

Even though the majority of existing users are probably only passing the first argument, it still seems a bad idea to break the API like this. Fragment parsing is also sufficiently different from document parsing to warrant a separate function.

Therefore, fragment parsing should be re-implemented as `gumbo.parseFragment` before the 0.4 release.

**Comment by craigbarnes** [comment]
This is the last issue blocking the release of 0.4.

**Comment by daurnimator** [comment]
perhaps just check the number of arguments (or types) for backwards compat?

**Comment by craigbarnes** [comment]
> perhaps just check the number of arguments (or types) for backwards compat?

The second argument for the new API is an optional string, checked via `luaL_optlstring`. The second argument for the old API was a number. If a number is passed as second argument to the new API, `luaL_optlstring` will coerce it to a string, which will then trigger fragment parsing mode (with `GumboOptions::fragment_context = GUMBO_TAG_UNKNOWN`).

**Comment by craigbarnes** [comment]
Perhaps just inserting a `luaL_argcheck()` to prevent coercion would be good enough...

**Comment by daurnimator** [comment]
> Perhaps just inserting a luaL_argcheck() to prevent coercion would be good enough...
or just use `lua_isstring`/`lua_type`

**Comment by craigbarnes** [comment]
Yeah, that seems like the best idea actually. I'll use your code and add a couple of test cases.

**Comment by craigbarnes** [comment]
I changed my mind about this. I really want to avoid accumulating hacks, so I did the simplest possible thing and just changed the order of arguments so that `tabStop` is in the same position as it was in 0.3.

**Comment by craigbarnes** [comment]
Fixed by `4b7a2374091eedfd54901ff533cf7ad3ac823a12`.

**Comment by craigbarnes** [comment]
I'll release o.4 tomorrow, barring any last minute bug reports.

**Comment by daurnimator** [comment]
> I changed my mind about this. I really want to avoid accumulating hacks, so I did the simplest possible thing and just changed the order of arguments so that tabStop is in the same position as it was in 0.3.

ehhh. I still like the way I mentioned.

I'd leave it in for one or 2 releases; then deprecate it.
With the current solution, you've diverged from upstream gumbo.

**Comment by craigbarnes** [comment]
> ... you've diverged from upstream gumbo

How so?

**Comment by daurnimator** [comment]
> How so?

In terms of function signatures.

**Comment by craigbarnes** [comment]
Which gumbo are we talking about? The C library or the Python bindings or...? In the C library, they're all just struct fields.

**Comment by daurnimator** [comment]
ah! I was thinking for another library then.

Infact, why don't you just have a table of options as the argument?

**Comment by craigbarnes** [comment]
> Infact, why don't you just have a table of options as the argument?

Back when gumbo was at version 0.9, there was only a single field in `GumboOptions` that was relevant to lua-gumbo (`tabStop`). It would have been odd to use a table for that. It may be worth breaking the API and using a table for something like #39, but for the sake of only 3 extra args, it doesn't seem worth it yet.
