### ISSUE TITLE
Add iterator methods for containers

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#52]
Adding member iterators for `NodeList`, `ElementList` and `AttributeList` could turn the following common pattern:

```lua
local childNodes = element.childNodes
for i = 1, #childNodes do
    local node = childNodes[i]
    -- Use node
end
```

...into:

```lua
for node in element.childNodes:iterate() do
    --- Use node
end
```

**Comment by daurnimator** [comment]
Is `iterate` a W3C standard thing?
Why not just provide an `__ipairs`?

**Comment by craigbarnes** [comment]
`iterate` isn't standard, no. I'm not sure what I was thinking when I posted this -- must have been a late night brain-dump. Even just the standard `ipairs` handles this fine.
