### ISSUE TITLE
No attribute.namespaceURI

### ISSUE THREAD

**Issue by daurnimator** [craigbarnes/lua-gumbo#54]
I was trying to get the namespace uri of an attribute, but `.namespaceURI` doesn't exist.

**Comment by craigbarnes** [comment]
I never got around to implementing/documenting this. If I remember correctly, HTML5 rules for attribute namespaces are not what most people would expect and quite different from XML. The exact details escape me at the moment, but I'll look into it shortly.

**Comment by craigbarnes** [comment]
There's now a getter for `Attribute.namespaceURI`.

Note: reading attributes that originate from input markup should work fine but adding and/or mutating namespaced attributes is currently not implemented.
