### ISSUE TITLE
error in install gumbo

### ISSUE THREAD

**Issue by sbh96** [craigbarnes/lua-gumbo#57]
i receive this error in install o ubuntu 16
```
sudo luarocks install gumbo
Installing https://luarocks.org/gumbo-0.4-1.rockspec

Error: Could not find header file for GUMBO
  No file gumbo.h in /usr/local/include
  No file gumbo.h in /usr/include
You may have to install GUMBO in your system and/or pass GUMBO_DIR or GUMBO_INCDIR to the luarocks command.
Example: luarocks install gumbo GUMBO_DIR=/usr/local
```
i try `Example: luarocks install gumbo GUMBO_DIR=/usr/local` but get me error
what is problem? thanks

**Comment by craigbarnes** [comment]
It tells you exactly what the problem is in the error message. You need to install [libgumbo](https://github.com/google/gumbo-parser/).
